### PR TITLE
fix(self-hosted): make Hivesigner login possible, and sign HiveAuth ops with the right authority

### PR DESCRIPTION
**Pull request by feruzm**
Part of #1316. Covers the Hivesigner half and the authority bug; the HiveAuth protocol rewrite is separate.

## Hivesigner login could not succeed on any hosted blog

The app sent `window.location.origin + window.location.pathname` as `redirect_uri`. OAuth matches it exactly, so every page produced a different URI — and none are registered on the `ecency.app` client, which lists only these (read from the account’s on-chain `posting_json_metadata`):

```
http://localhost:3000/auth
https://ecency.com/auth
https://alpha.ecency.com/auth
https://chat.ecency.com/_oauth/hivesigner
```

A tenant origin cannot be pre-registered either, since custom domains are unbounded.

- **Fixed `/auth` redirect path**, so one URI per origin is all that needs registering. That is the most a self-hoster on their own domain can register, and it is what makes registration viable at all.
- **Per-instance client id** (`general.hivesigner.clientId`), so an owner who registers their own app can use it.
- **The method is not offered when the instance has no usable client.** A button that always fails is worse than no button.

## The callback accepted URL input as a credential

It was handled by an effect running on *every* route, so any page carrying `?access_token=&username=` counted as a completed login. A crafted link signed the visitor in as whoever the token belonged to, and everything they wrote afterwards was attributed to that account.

It now has a dedicated `/auth` route that requires a `state` nonce it issued itself and verifies the token actually belongs to the claimed account before storing a session. Both fail closed.

## HiveAuth signed everything with posting authority

The adapter received the key type as `_keyType` and the util hardcoded `posting`. The chain rejects a transfer signed with posting authority, so tips, transfers and any `custom_json` with `required_auths` could not work through HiveAuth regardless of the protocol fix. The requested authority is now passed through.

## Notes

- `resolveHivesignerClientId` is pure and takes the configured value rather than reading config itself, so the rule lives in one place and is testable without the config module.
- Removed `redirectToHivesigner`, which had no callers and would have bypassed both the fixed path and the nonce.
- **Still broken, tracked in #1316 and being fixed separately:** the HiveAuth client does not implement the HAS protocol (unencrypted `auth_req.data`, `auth_ack` read as plaintext, `hiveauth://auth/` instead of `has://auth_req/`), so HiveAuth login still cannot complete. Until that lands, Keychain remains the only working method unless an owner registers their own Hivesigner app.

## Verification

13 new tests, mutation-checked: removing the nonce check fails 3, removing the token ownership check fails 1, offering the built-in client fails 2, dropping the authority fails 2. 139 tests pass, typecheck clean, build succeeds, and the per-rule lint diff against develop is empty.

## Summary by CodeRabbit

- **New Features**
  - Added configurable Hivesigner client IDs for self-hosted instances.
  - Added a dedicated authentication flow with secure callback validation and clearer loading, cancellation, and failure handling.
  - Hivesigner now appears only when configured and supports localized login failure messages.
  - Added support for broadcasting actions with the appropriate Hive authority, including active, owner, and memo keys.
- **Bug Fixes**
  - Improved OAuth state and token verification to reject invalid or unsolicited login attempts.

### CODE REVIEW

File: apps/self-hosted/src/routes/auth.tsx [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+  useEffect(() => {
+    let cancelled = false;
+
+    async function completeLogin() {
+      const search = window.location.search;
+      const params = new URLSearchParams(search);
+      const callback = parseHivesignerCallback(search);
+
+      // Consumed unconditionally so a failed attempt cannot be replayed.
+      const stateOk = consumeHivesignerState(params.get('state'));
```
[the remark this answers is not in the document]
Comment (feruzm) [reply apps/self-hosted/src/routes/auth.tsx]: Confirmed and fixed. The callback is now read once per page load and every caller shares that single attempt, so the replay awaits the first one instead of finding the nonce already consumed. Moved into `hivesigner-callback.ts` so it can be tested without booting the router; removing the shared attempt fails the test.

File: apps/self-hosted/src/routes/auth.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+        loginType: 'hivesigner',
+        expiresAt: Date.now() + callback.expiresIn * 1000,
+      };
+      setUser(user);
+      saveUser(user);
+
+      // Drop the credential from the address bar before leaving this page.
+      window.history.replaceState({}, '', window.location.pathname);
+      navigate({ to: '/blog', search: { filter: 'posts' } });
+    }
```
[the remark this answers is not in the document]
Comment (feruzm) [reply apps/self-hosted/src/routes/auth.tsx]: Agreed, fixed. The URL is now cleared as soon as the callback is read, before any validation branch.

Worth noting the two findings could not be fixed independently. Clearing the URL first changes what the StrictMode replay reads, so the shared-attempt fix would have gone back to rejecting valid logins. Both now live in one place: `completeHivesignerCallback()` reads `window.location.search` and clears it once per page load, then all callers share that attempt. Reverting either half fails a test.

File: apps/self-hosted/src/routes/auth.tsx [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+
+    completeLogin();
+    return () => {
+      cancelled = true;
+    };
+  }, [navigate, setUser]);
```
[the remark this answers is not in the document]
Comment (feruzm) [reply apps/self-hosted/src/routes/auth.tsx:49]: Same finding as the Codex bot on this file, fixed together with the URL stripping in the other thread. The two could not be fixed independently: clearing the URL first changes what the StrictMode replay reads, so the shared-attempt fix alone would have gone back to rejecting valid logins. Both now live in `completeHivesignerCallback()`, which reads the callback and clears the URL once per page load.
